# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

# ignore all warnings from all pods
inhibit_all_warnings!

xcodeproj 'captureWebHref'

# Pods  
pod 'BlocksKit'
pod 'MBProgressHUD’



